name: code_checks

on: [push, pull_request]

jobs:

  check_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: JohnnyMorganz/stylua-action@v1
      with:
        version: 0.15.1
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup 
      run: |
        sudo apt install luarocks -qyy
        sudo luarocks install luacheck
    - name: lint
      run: |
        luacheck .

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v4

    - name: setup 
      run: |
        luarocks install busted

    - name: test
      run: |
        busted -o utfTerminal .spec
